### ISSUE TITLE
“=” in links ([url] tag values) is marked as an error

### ISSUE THREAD

**Issue by slavalamp** [Tabuu/Bulletin-Board-Code-TextMate#1]
If you have a link with URL variables, for example `[url=https://www.youtube.com/watch?v=dQw4w9WgXcQ]link[/url]`, =’s style in it is different
![image](https://user-images.githubusercontent.com/53832230/85128429-edc1c300-b239-11ea-8c28-62edb34e3e2a.png)

**Comment by Tabuu** [comment]
I'll consider this a bug since in BBCode, as opposed to HTML, most interpreters won't accept quoted variables (e.g. `[url='https://www.youtube.com/watch?v=dQw4w9WgXcQ']link[/url]`).

**Comment by Tabuu** [comment]
The update has been [released](https://github.com/Tabuu/Bulletin-Board-Code-TextMate/releases/tag/0.0.2).
